export const words = [
  { word: 'keyboard', category: 'Technology' },
  { word: 'headphones', category: 'Technology' },
  { word: 'computer', category: 'Technology' },
  { word: 'camera', category: 'Technology' },
  { word: 'mouse', category: 'Technology' },
  { word: 'phone', category: 'Technology' },
  { word: 'router', category: 'Technology' },
  { word: 'calculator', category: 'Technology' },
  { word: 'antenna', category: 'Technology' },
  { word: 'webcam', category: 'Technology' },
  { word: 'microphone', category: 'Technology' },
  { word: 'floppy', category: 'Technology' },

  { word: 'car', category: 'Transport' },
  { word: 'plane', category: 'Transport' },
  { word: 'ship', category: 'Transport' },
  { word: 'helicopter', category: 'Transport' },
  { word: 'boat', category: 'Transport' },
  { word: 'bike', category: 'Transport' },
  { word: 'tram', category: 'Transport' },
  { word: 'taxi', category: 'Transport' },
  { word: 'ambulance', category: 'Transport' },
  { word: 'van', category: 'Transport' },
  { word: 'campervan', category: 'Transport' },
  { word: 'bus', category: 'Transport' },

  { word: 'pizza', category: 'Food' },
  { word: 'fries', category: 'Food' },
  { word: 'pineapple', category: 'Food' },
  { word: 'apple', category: 'Food' },
  { word: 'bread', category: 'Food' },
  { word: 'burger', category: 'Food' },
  { word: 'curry', category: 'Food' },
  { word: 'rice', category: 'Food' },
  { word: 'lettuce', category: 'Food' },
  { word: 'sweets', category: 'Food' },
  { word: 'donut', category: 'Food' },
  { word: 'cupcake', category: 'Food' },

  { word: 'nurse', category: 'Job' },
  { word: 'fireman', category: 'Job' },
  { word: 'doctor', category: 'Job' },
  { word: 'policeman', category: 'Job' },
  { word: 'teacher', category: 'Job' },
  { word: 'developer', category: 'Job' },
  { word: 'gravedigger', category: 'Job' },
  { word: 'dancer', category: 'Job' },
  { word: 'baker', category: 'Job' },
  { word: 'referee', category: 'Job' },
  { word: 'chief', category: 'Job' },
  { word: 'writer', category: 'Job' },

  { word: 'deer', category: 'Animal' },
  { word: 'elephant', category: 'Animal' },
  { word: 'rhino', category: 'Animal' },
  { word: 'bear', category: 'Animal' },
  { word: 'horse', category: 'Animal' },
  { word: 'donkey', category: 'Animal' },
  { word: 'goat', category: 'Animal' },
  { word: 'giraffe', category: 'Animal' },
  { word: 'cheetah', category: 'Animal' },
  { word: 'squirrel', category: 'Animal' },
  { word: 'camel', category: 'Animal' },
  { word: 'fox', category: 'Animal' },
];
