export const words = [
  { word: 'keyboard', category: 'Technology' },
  { word: 'headphones', category: 'Technology' },
  { word: 'computer', category: 'Technology' },
  { word: 'camera', category: 'Technology' },
  { word: 'mouse', category: 'Technology' },
  { word: 'phone', category: 'Technology' },
  { word: 'router', category: 'Technology' },
  { word: 'calculator', category: 'Technology' },
  { word: 'antenna', category: 'Technology' },
  { word: 'webcam', category: 'Technology' },
  { word: 'microphone', category: 'Technology' },
  { word: 'floppy', category: 'Technology' },

  { word: 'car', category: 'Transport' },
  { word: 'plane', category: 'Transport' },
  { word: 'ship', category: 'Transport' },
  { word: 'helicopter', category: 'Transport' },
  { word: 'boat', category: 'Transport' },
  { word: 'bike', category: 'Transport' },
  { word: 'tram', category: 'Transport' },
  { word: 'taxi', category: 'Transport' },
  { word: 'ambulance', category: 'Transport' },
  { word: 'van', category: 'Transport' },
  { word: 'campervan', category: 'Transport' },
  { word: 'bus', category: 'Transport' },

  { word: 'pizza', category: 'Food' },
  { word: 'fries', category: 'Food' },
  { word: 'pineapple', category: 'Food' },
  { word: 'apple', category: 'Food' },
  { word: 'bread', category: 'Food' },
  { word: 'burger', category: 'Food' },
  { word: 'curry', category: 'Food' },
  { word: 'rice', category: 'Food' },
  { word: 'lettuce', category: 'Food' },
  { word: 'sweets', category: 'Food' },
  { word: 'donut', category: 'Food' },
  { word: 'cupcake', category: 'Food' },

  { word: 'nurse', category: 'Job' },
  { word: 'fireman', category: 'Job' },
  { word: 'doctor', category: 'Job' },
  { word: 'policeman', category: 'Job' },
  { word: 'teacher', category: 'Job' },
  { word: 'developer', category: 'Job' },
  { word: 'gravedigger', category: 'Job' },
  { word: 'dancer', category: 'Job' },
  { word: 'baker', category: 'Job' },
  { word: 'referee', category: 'Job' },
  { word: 'chief', category: 'Job' },
  { word: 'writer', category: 'Job' },

  { word: 'deer', category: 'Animal' },
  { word: 'elephant', category: 'Animal' },
  { word: 'rhino', category: 'Animal' },
  { word: 'bear', category: 'Animal' },
  { word: 'horse', category: 'Animal' },
  { word: 'donkey', category: 'Animal' },
  { word: 'goat', category: 'Animal' },
  { word: 'giraffe', category: 'Animal' },
  { word: 'cheetah', category: 'Animal' },
  { word: 'squirrel', category: 'Animal' },
  { word: 'camel', category: 'Animal' },
  { word: 'fox', category: 'Animal' },

  { word: 'soccer', category: 'Sports' },
  { word: 'tennis', category: 'Sports' },
  { word: 'basketball', category: 'Sports' },
  { word: 'volleyball', category: 'Sports' },
  { word: 'hockey', category: 'Sports' },
  { word: 'baseball', category: 'Sports' },
  { word: 'rugby', category: 'Sports' },
  { word: 'swimming', category: 'Sports' },
  { word: 'gymnastics', category: 'Sports' },
  { word: 'skiing', category: 'Sports' },
  { word: 'snowboarding', category: 'Sports' },
  { word: 'surfing', category: 'Sports' },

  { word: 'guitar', category: 'Music' },
  { word: 'piano', category: 'Music' },
  { word: 'drums', category: 'Music' },
  { word: 'bass', category: 'Music' },
  { word: 'saxophone', category: 'Music' },
  { word: 'trumpet', category: 'Music' },
  { word: 'violin', category: 'Music' },
  { word: 'flute', category: 'Music' },
  { word: 'harmonica', category: 'Music' },
  { word: 'ukulele', category: 'Music' },
  { word: 'banjo', category: 'Music' },
  { word: 'synthesizer', category: 'Music' },

  { word: 'europe', category: 'Geography' },
  { word: 'asia', category: 'Geography' },
  { word: 'africa', category: 'Geography' },
  { word: 'north america', category: 'Geography' },
  { word: 'south america', category: 'Geography' },
  { word: 'antarctica', category: 'Geography' },
  { word: 'australia', category: 'Geography' },
  { word: 'mount everest', category: 'Geography' },
  { word: 'great barrier reef', category: 'Geography' },
  { word: 'grand canyon', category: 'Geography' },

  { word: 'art', category: 'Culture' },
  { word: 'literature', category: 'Culture' },
  { word: 'cinema', category: 'Culture' },
  { word: 'theater', category: 'Culture' },
  { word: 'music', category: 'Culture' },
  { word: 'dance', category: 'Culture' },
  { word: 'fashion', category: 'Culture' },
  { word: 'food', category: 'Culture' },
  { word: 'architecture', category: 'Culture' },
  { word: 'museums', category: 'Culture' },
  { word: 'photography', category: 'Culture' },
  { word: 'history', category: 'Culture' },

  { word: 'mountain', category: 'Nature' },
  { word: 'river', category: 'Nature' },
  { word: 'ocean', category: 'Nature' },
  { word: 'forest', category: 'Nature' },
  { word: 'desert', category: 'Nature' },
  { word: 'waterfall', category: 'Nature' },
  { word: 'canyon', category: 'Nature' },
  { word: 'island', category: 'Nature' },
  { word: 'wildlife', category: 'Nature' },
  { word: 'beach', category: 'Nature' },
  { word: 'clouds', category: 'Nature' },
  { word: 'sunset', category: 'Nature' },

  { word: 'chair', category: 'Household Items' },
  { word: 'table', category: 'Household Items' },
  { word: 'lamp', category: 'Household Items' },
  { word: 'sofa', category: 'Household Items' },
  { word: 'mirror', category: 'Household Items' },
  { word: 'clock', category: 'Household Items' },
  { word: 'vacuum', category: 'Household Items' },
  { word: 'dish', category: 'Household Items' },
  { word: 'picture', category: 'Household Items' },
  { word: 'knife', category: 'Household Items' },
  { word: 'fork', category: 'Household Items' },
  { word: 'spoon', category: 'Household Items' },
];
