export const words = [
  { word: 'keyboard', category: 'Technology' },
  { word: 'headphones', category: 'Technology' },
  { word: 'computer', category: 'Technology' },
  { word: 'camera', category: 'Technology' },
  { word: 'mouse', category: 'Technology' },
  { word: 'phone', category: 'Technology' },
  { word: 'router', category: 'Technology' },
  { word: 'calculator', category: 'Technology' },
  { word: 'antenna', category: 'Technology' },
  { word: 'webcam', category: 'Technology' },
  { word: 'microphone', category: 'Technology' },
  { word: 'floppy', category: 'Technology' },
  { word: 'tablet', category: 'Technology' },
  { word: 'smartwatch', category: 'Technology' },
  { word: 'monitor', category: 'Technology' },
  { word: 'printer', category: 'Technology' },
  { word: 'projector', category: 'Technology' },

  { word: 'car', category: 'Transport' },
  { word: 'plane', category: 'Transport' },
  { word: 'ship', category: 'Transport' },
  { word: 'helicopter', category: 'Transport' },
  { word: 'boat', category: 'Transport' },
  { word: 'bike', category: 'Transport' },
  { word: 'tram', category: 'Transport' },
  { word: 'taxi', category: 'Transport' },
  { word: 'ambulance', category: 'Transport' },
  { word: 'van', category: 'Transport' },
  { word: 'campervan', category: 'Transport' },
  { word: 'bus', category: 'Transport' },
  { word: 'scooter', category: 'Transport' },
  { word: 'motorcycle', category: 'Transport' },
  { word: 'skateboard', category: 'Transport' },
  { word: 'train', category: 'Transport' },
  { word: 'subway', category: 'Transport' },

  { word: 'pizza', category: 'Food' },
  { word: 'fries', category: 'Food' },
  { word: 'pineapple', category: 'Food' },
  { word: 'apple', category: 'Food' },
  { word: 'bread', category: 'Food' },
  { word: 'burger', category: 'Food' },
  { word: 'curry', category: 'Food' },
  { word: 'rice', category: 'Food' },
  { word: 'lettuce', category: 'Food' },
  { word: 'sweets', category: 'Food' },
  { word: 'donut', category: 'Food' },
  { word: 'cupcake', category: 'Food' },
  { word: 'taco', category: 'Food' },
  { word: 'lasagna', category: 'Food' },
  { word: 'spaghetti', category: 'Food' },
  { word: 'cheese', category: 'Food' },
  { word: 'nachos', category: 'Food' },
  { word: 'pancake', category: 'Food' },
  { word: 'soup', category: 'Food' },
  { word: 'sandwich', category: 'Food' },

  { word: 'nurse', category: 'Job' },
  { word: 'fireman', category: 'Job' },
  { word: 'doctor', category: 'Job' },
  { word: 'policeman', category: 'Job' },
  { word: 'teacher', category: 'Job' },
  { word: 'developer', category: 'Job' },
  { word: 'gravedigger', category: 'Job' },
  { word: 'dancer', category: 'Job' },
  { word: 'baker', category: 'Job' },
  { word: 'referee', category: 'Job' },
  { word: 'chief', category: 'Job' },
  { word: 'writer', category: 'Job' },
  { word: 'architect', category: 'Job' },
  { word: 'dentist', category: 'Job' },
  { word: 'pharmacist', category: 'Job' },
  { word: 'plumber', category: 'Job' },
  { word: 'barista', category: 'Job' },
  { word: 'journalist', category: 'Job' },
  { word: 'cashier', category: 'Job' },
  { word: 'librarian', category: 'Job' },

  { word: 'deer', category: 'Animal' },
  { word: 'elephant', category: 'Animal' },
  { word: 'rhino', category: 'Animal' },
  { word: 'bear', category: 'Animal' },
  { word: 'horse', category: 'Animal' },
  { word: 'donkey', category: 'Animal' },
  { word: 'goat', category: 'Animal' },
  { word: 'giraffe', category: 'Animal' },
  { word: 'cheetah', category: 'Animal' },
  { word: 'squirrel', category: 'Animal' },
  { word: 'camel', category: 'Animal' },
  { word: 'fox', category: 'Animal' },
  { word: 'zebra', category: 'Animal' },
  { word: 'kangaroo', category: 'Animal' },
  { word: 'koala', category: 'Animal' },
  { word: 'platypus', category: 'Animal' },
  { word: 'lemur', category: 'Animal' },
  { word: 'otter', category: 'Animal' },
  { word: 'tiger', category: 'Animal' },
  { word: 'walrus', category: 'Animal' },

  { word: 'soccer', category: 'Sports' },
  { word: 'tennis', category: 'Sports' },
  { word: 'basketball', category: 'Sports' },
  { word: 'volleyball', category: 'Sports' },
  { word: 'hockey', category: 'Sports' },
  { word: 'baseball', category: 'Sports' },
  { word: 'rugby', category: 'Sports' },
  { word: 'swimming', category: 'Sports' },
  { word: 'gymnastics', category: 'Sports' },
  { word: 'skiing', category: 'Sports' },
  { word: 'snowboarding', category: 'Sports' },
  { word: 'surfing', category: 'Sports' },
  { word: 'golf', category: 'Sports' },
  { word: 'boxing', category: 'Sports' },
  { word: 'cricket', category: 'Sports' },
  { word: 'fencing', category: 'Sports' },
  { word: 'karate', category: 'Sports' },
  { word: 'judo', category: 'Sports' },
  { word: 'badminton', category: 'Sports' },
  { word: 'cycling', category: 'Sports' },

  { word: 'guitar', category: 'Music' },
  { word: 'piano', category: 'Music' },
  { word: 'drums', category: 'Music' },
  { word: 'bass', category: 'Music' },
  { word: 'saxophone', category: 'Music' },
  { word: 'violin', category: 'Music' },
  { word: 'flute', category: 'Music' },
  { word: 'harmonica', category: 'Music' },
  { word: 'banjo', category: 'Music' },
  { word: 'trumpet', category: 'Music' },
  { word: 'trombone', category: 'Music' },
  { word: 'accordion', category: 'Music' },
  { word: 'clarinet', category: 'Music' },
  { word: 'ukulele', category: 'Music' },
  { word: 'synthesizer', category: 'Music' },

  { word: 'europe', category: 'Geography' },
  { word: 'asia', category: 'Geography' },
  { word: 'africa', category: 'Geography' },
  { word: 'antarctica', category: 'Geography' },
  { word: 'australia', category: 'Geography' },
  { word: 'england', category: 'Geography' },
  { word: 'france', category: 'Geography' },
  { word: 'germany', category: 'Geography' },
  { word: 'spain', category: 'Geography' },
  { word: 'japan', category: 'Geography' },
  { word: 'brazil', category: 'Geography' },
  { word: 'russia', category: 'Geography' },
  { word: 'china', category: 'Geography' },
  { word: 'india', category: 'Geography' },
  { word: 'canada', category: 'Geography' },
  { word: 'mexico', category: 'Geography' },
  { word: 'italy', category: 'Geography' },
  { word: 'australia', category: 'Geography' },
  { word: 'greece', category: 'Geography' },
  { word: 'egypt', category: 'Geography' },
  { word: 'switzerland', category: 'Geography' },
  { word: 'netherlands', category: 'Geography' },
  { word: 'sweden', category: 'Geography' },

  { word: 'art', category: 'Culture' },
  { word: 'literature', category: 'Culture' },
  { word: 'cinema', category: 'Culture' },
  { word: 'theater', category: 'Culture' },
  { word: 'music', category: 'Culture' },
  { word: 'dance', category: 'Culture' },
  { word: 'fashion', category: 'Culture' },
  { word: 'food', category: 'Culture' },
  { word: 'architecture', category: 'Culture' },
  { word: 'museums', category: 'Culture' },
  { word: 'photography', category: 'Culture' },
  { word: 'history', category: 'Culture' },

  { word: 'mountain', category: 'Nature' },
  { word: 'river', category: 'Nature' },
  { word: 'ocean', category: 'Nature' },
  { word: 'forest', category: 'Nature' },
  { word: 'desert', category: 'Nature' },
  { word: 'waterfall', category: 'Nature' },
  { word: 'canyon', category: 'Nature' },
  { word: 'island', category: 'Nature' },
  { word: 'wildlife', category: 'Nature' },
  { word: 'beach', category: 'Nature' },
  { word: 'clouds', category: 'Nature' },
  { word: 'sunset', category: 'Nature' },
  { word: 'volcano', category: 'nature' },
  { word: 'tundra', category: 'nature' },
  { word: 'prairie', category: 'nature' },
  { word: 'marsh', category: 'nature' },
  { word: 'lake', category: 'nature' },
  { word: 'cave', category: 'nature' },
  { word: 'glacier', category: 'nature' },
  { word: 'reef', category: 'nature' },
  { word: 'swamp', category: 'nature' },
  { word: 'rainforest', category: 'nature' },

  { word: 'action', category: 'Movies' },
  { word: 'adventure', category: 'Movies' },
  { word: 'animation', category: 'Movies' },
  { word: 'comedy', category: 'Movies' },
  { word: 'crime', category: 'Movies' },
  { word: 'documentary', category: 'Movies' },
  { word: 'drama', category: 'Movies' },
  { word: 'family', category: 'Movies' },
  { word: 'fantasy', category: 'Movies' },
  { word: 'filmnoir', category: 'Movies' },
  { word: 'history', category: 'Movies' },
  { word: 'horror', category: 'Movies' },
  { word: 'music', category: 'Movies' },
  { word: 'musical', category: 'Movies' },
  { word: 'mystery', category: 'Movies' },
  { word: 'romance', category: 'Movies' },
  { word: 'scifi', category: 'Movies' },
  { word: 'sport', category: 'Movies' },
  { word: 'thriller', category: 'Movies' },
  { word: 'war', category: 'Movies' },

  { word: 'biology', category: 'Science' },
  { word: 'chemistry', category: 'Science' },
  { word: 'physics', category: 'Science' },
  { word: 'geology', category: 'Science' },
  { word: 'astronomy', category: 'Science' },
  { word: 'meteorology', category: 'Science' },
  { word: 'zoology', category: 'Science' },
  { word: 'botany', category: 'Science' },
  { word: 'ecology', category: 'Science' },
  { word: 'psychology', category: 'Science' },
  { word: 'neuroscience', category: 'Science' },
  { word: 'nanotechnology', category: 'Science' },
  { word: 'genetics', category: 'Science' },
  { word: 'evolution', category: 'Science' },
  { word: 'oceanography', category: 'Science' },
  { word: 'archaeology', category: 'Science' },
  { word: 'anatomy', category: 'Science' },
  { word: 'microbiology', category: 'Science' },
  { word: 'optics', category: 'Science' },

  { word: 'gardening', category: 'Hobbies' },
  { word: 'painting', category: 'Hobbies' },
  { word: 'drawing', category: 'Hobbies' },
  { word: 'photography', category: 'Hobbies' },
  { word: 'knitting', category: 'Hobbies' },
  { word: 'cooking', category: 'Hobbies' },
  { word: 'baking', category: 'Hobbies' },
  { word: 'reading', category: 'Hobbies' },
  { word: 'writing', category: 'Hobbies' },
  { word: 'hiking', category: 'Hobbies' },
  { word: 'camping', category: 'Hobbies' },
  { word: 'fishing', category: 'Hobbies' },
  { word: 'woodworking', category: 'Hobbies' },
  { word: 'pottery', category: 'Hobbies' },
  { word: 'scrapbooking', category: 'Hobbies' },
  { word: 'dancing', category: 'Hobbies' },
  { word: 'swimming', category: 'Hobbies' },
  { word: 'running', category: 'Hobbies' },
  { word: 'cycling', category: 'Hobbies' },
  { word: 'yoga', category: 'Hobbies' },

  { word: 'astronaut', category: 'Space' },
  { word: 'galaxy', category: 'Space' },
  { word: 'comet', category: 'Space' },
  { word: 'nebula', category: 'Space' },
  { word: 'satellite', category: 'Space' },
  { word: 'telescope', category: 'Space' },
  { word: 'planet', category: 'Space' },
  { word: 'star', category: 'Space' },
  { word: 'blackhole', category: 'Space' },
  { word: 'meteor', category: 'Space' },
  { word: 'wheel', category: 'Inventions' },
  { word: 'telephone', category: 'Inventions' },
  { word: 'internet', category: 'Inventions' },
  { word: 'airplane', category: 'Inventions' },
  { word: 'automobile', category: 'Inventions' },
  { word: 'refrigeration', category: 'Inventions' },
  { word: 'television', category: 'Inventions' },

  { word: 'red', category: 'colors' },
  { word: 'blue', category: 'colors' },
  { word: 'green', category: 'colors' },
  { word: 'yellow', category: 'colors' },
  { word: 'orange', category: 'colors' },
  { word: 'purple', category: 'colors' },
  { word: 'pink', category: 'colors' },
  { word: 'brown', category: 'colors' },
  { word: 'black', category: 'colors' },
  { word: 'white', category: 'colors' },
  { word: 'gray', category: 'colors' },
  { word: 'turquoise', category: 'colors' },
  { word: 'indigo', category: 'colors' },
  { word: 'gold', category: 'colors' },
  { word: 'silver', category: 'colors' },
  { word: 'bronze', category: 'colors' },

  { word: 'head', category: 'body parts' },
  { word: 'neck', category: 'body parts' },
  { word: 'shoulder', category: 'body parts' },
  { word: 'arm', category: 'body parts' },
  { word: 'elbow', category: 'body parts' },
  { word: 'wrist', category: 'body parts' },
  { word: 'hand', category: 'body parts' },
  { word: 'finger', category: 'body parts' },
  { word: 'chest', category: 'body parts' },
  { word: 'back', category: 'body parts' },
  { word: 'stomach', category: 'body parts' },
  { word: 'waist', category: 'body parts' },
  { word: 'hip', category: 'body parts' },
  { word: 'leg', category: 'body parts' },
  { word: 'thigh', category: 'body parts' },
  { word: 'knee', category: 'body parts' },
  { word: 'ankle', category: 'body parts' },
  { word: 'foot', category: 'body parts' },

  { word: 'circle', category: 'shapes' },
  { word: 'triangle', category: 'shapes' },
  { word: 'square', category: 'shapes' },
  { word: 'rectangle', category: 'shapes' },
  { word: 'pentagon', category: 'shapes' },
  { word: 'hexagon', category: 'shapes' },
  { word: 'heptagon', category: 'shapes' },
  { word: 'octagon', category: 'shapes' },
  { word: 'decagon', category: 'shapes' },
  { word: 'ellipse', category: 'shapes' },
  { word: 'oval', category: 'shapes' },
  { word: 'rhombus', category: 'shapes' },
];
